trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run test
  displayName: 'Install dependencies & Run Tests'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'my-container-registry/my-app'
    dockerfile: 'Dockerfile'
