trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies & build frontend'

- stage: Test
  jobs:
  - job: Run_Tests
    steps:
    - script: npm test
      displayName: 'Run Unit Tests'

- stage: Deploy
  jobs:
  - job: Deploy_Frontend
    steps:
    - task: AzureStaticWebApp@1
      inputs:
        app_name: 'ui'
        resource_group: 'MyResourceGroup'
        location: 'eastus'
        output_location: 'frontend/build'
  
  - job: Deploy_Backend
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'YourAzureSubscription'
        appName: 'api'
        package: '$(System.DefaultWorkingDirectory)/backend'
